    <!-- bizsolo generate="false" -->
        <%--  This JSP has been generated by using from xsl version 9.0 at Fri Jul 08 16:39:57 COT 2016 --%>
        <!DOCTYPE html>
        <html xmlns:c="http://java.sun.com/jsp/jstl/core" xmlns:sfe="http://www.savvion.com/sbm/sfe"
        xmlns:jsp="http://java.sun.com/JSP/Page" xmlns:xalan="http://xml.apache.org/xalan"
        xmlns:fn="http://www.w3.org/2005/02/xpath-functions" xmlns:bizsolo="http://www.savvion.com/sbm/BizSolo"
        xmlns:sbm="http://www.savvion.com/sbm">
        <head><META http-equiv="Content-Type" content="text/html; charset=utf-8">

        <%@ page contentType="text/html; charset=UTF-8" %>
        <%@ page
                import="com.savvion.BizSolo.Server.*,com.savvion.BizSolo.beans.*,com.savvion.sbm.util.DatabaseMapping,java.util.Vector,java.util.Locale" %>
        <%@ page import="com.savvion.sbm.bizsolo.util.session.*,java.net.*" %>
        <%@ page errorPage="/BizSolo/common/jsp/expcontroller.jsp" %>
        <%@ taglib uri="/BizSolo/common/tlds/bizsolo.tld" prefix="bizsolo" %>
        <%@ taglib uri="/bpmportal/tld/bpmportal.tld" prefix="sbm" %>
        <%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
        <%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
        <%@ taglib prefix="form" tagdir="/WEB-INF/tags/form" %>
        <%@ taglib prefix="sfe" uri="http://jmaki/v1.0/jsp" %>
        <%@ include file="/BizSolo/common/jsp/include_i18n_msgs.jsp" %>
        <jsp:useBean id="bizManage" class="com.savvion.sbm.bizmanage.api.BizManageBean" scope="session"></jsp:useBean>
        <jsp:useBean id="bean" class="com.savvion.BizSolo.beans.Bean" scope="session"></jsp:useBean>
        <jsp:useBean id="factoryBean" class="com.savvion.BizSolo.beans.EPFactoryBean" scope="session"></jsp:useBean>
        <jsp:useBean id="bizSite" class="com.savvion.sbm.bpmportal.bizsite.api.BizSiteBean"
                     scope="session"></jsp:useBean>
            <%! String _PageName = "Activity 1"; %>
            <%! String __webAppName = "Documentos"; %>
            <% pageContext.setAttribute( "contextPath", request.getContextPath()+"/"); %>
            <% pageContext.setAttribute( "maxMulitLineLength", DatabaseMapping.self().getSQLSize(java.lang.String.class));  %>
            <%java.util.List<String> priorities = com.savvion.sbm.bpmportal.util.PortalUtil.self().getPriorities();%>
            <% pageContext.setAttribute( "_priorities",priorities); %>

        <title>Activity 1</title>
            <%boolean isStandaloneBS = (bizManage == null || bizManage.getName() == null || "".equals(bizManage.getName()) || bizManage.getLocale() == null);Locale myLocale = (!isStandaloneBS) ? bizManage.getLocale() : request.getLocale();%>
        <!-- Javascript -->
        <script language="JavaScript"> var getLocalizedString = parent.getLocalizedString; </script>
        <form:includes contextPath="${contextPath}"/>
        <script language="JavaScript">
        Ext.BLANK_IMAGE_URL = '<c:out value='${contextPath}'/>bpmportal/javascript/ext/resources/images/default/s.gif';

        var isIFrame
        =<%= (PublicResources.INTERACTIVE_MODE.equalsIgnoreCase(bean.getPropString(PublicResources.MODE)) || PublicResources.SLAVE_MODE.equalsIgnoreCase(bean.getPropString(PublicResources.MODE))) ? true : false %>
        ;


        function getContextPath(){
        return "<%=request.getContextPath()%>";
        }
        </script>
        <link rel="stylesheet" type="text/css" href="css/kendo.common.min.css">
        <link rel="stylesheet" type="text/css" href="css/kendo.default.min.css">
        <link rel="stylesheet" type="text/css" href="css/estilos.css">

        <sbm:setLocale value="<%= bizManage.getLocale() %>"></sbm:setLocale>
            <% try{ %>
        <sbm:setBundle scope="page" basename="Documentos/properties/Documentos"></sbm:setBundle>
            <% } catch(Exception e){}%>
        <bizsolo:getApplicationResources baseName="Documentos/properties/Documentos"/></head>
        <body class="apbody yui-skin-sam"
        onLoad="setCheckBoxStyleForIE();hideControls();beforeInitControls();initControls();initTabs();sbm.utils.onDOMReady();">
        <form method="post" name="form" onsubmit="return sbm.utils.onFormSubmit();">
        <div id="northDiv"><bizsolo:xsrf/></div><% /* Workaround, activityName will disappear in the future */ %>
            <% String activityName = bean.getPropString("workitemName"); %>
        <div id="resultDiv">
        <div style='visibility:hidden;display:none' class='vBoxClass' name='errors' id='errors'></div>
        <input name="crtPage" type="hidden" value="Activity1"><input name="crtApp" type="hidden"
        value="Documentos"><input name="activityMode" type="hidden" value="procReq"><input type="hidden" name="nextPage"
        value="Start.jsp">
        <input name="_yahoo_flow_button" type="hidden" value=''>
        <!-- Content -->


        <table align="left" cellpadding="1" cellspacing="1" class="fondogris1" id="table1" width="100%">
        <colgroup span="1">
        <col width="70px" span="1">
        <col span="1">
        </colgroup>
        <tbody>
        <tr>
        <td align="left" class="espacio" valign="middle" rowspan="1" colspan="1">
        <div align="left" id="">
        <img border="0" id="image01" width="51" height="46" src="images/Nav-64.png" tabindex="0">
        </div>
        </td>
        <td align="left" class="default" valign="middle" rowspan="1" colspan="1">
        <div align="left" id="">
        <font color="#ffffff" face="Arial" size="4">Documentos</font>
        </div>
        </td>
        </tr>
        </tbody>
        </table>

        <br clear="all">
        <br clear="all">
        <br clear="all">
        <br clear="all">
        <br clear="all">
        <table align="left" cellpadding="1" cellspacing="1" class="ApSegDataTbl" id="table1" width="100%">
        <colgroup span="1">
        <col width="70px" span="1">
        <col width="80px" span="1">
        <col span="1">
        <col width="150px" span="1">
        </colgroup>
        <tbody>
        <tr>
        <td align="left" class="default" valign="top" rowspan="1" colspan="1">
        <div align="left" id="">

        <!--<head>


        <meta charset="utf-8">


        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.common.min.css">


        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.rtl.min.css">


        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.default.min.css">


        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.dataviz.min.css">


        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.dataviz.default.min.css">


        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.mobile.all.min.css">


        <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>


        <script src="http://cdn.kendostatic.com/2015.2.624/js/kendo.all.min.js"></script>


        </head>
        -->


        </div>
        </td>
        <td align="left" class="default" valign="top" rowspan="1" colspan="1">
        <div align="left" id="">
        <div align="right" id=""></div>
        </div>
        </td>
        <td align="left" class="default" colspan="2" valign="top" rowspan="1">
        <div align="left" id="">

        <!--<head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.common.min.css">
        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.rtl.min.css">
        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.default.min.css">
        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.dataviz.min.css">
        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.dataviz.default.min.css">
        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.mobile.all.min.css">


        <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
        <script src="http://cdn.kendostatic.com/2015.2.624/js/kendo.all.min.js"></script>

        <script type="text/javascript" src="scripts/jspdf.js"></script>
        <script type="text/javascript" src="scripts/jspdf.plugin.standard_fonts_metrics.js"></script>
        <script type="text/javascript" src="scripts/jspdf.plugin.split_text_to_size.js"></script>
        <script type="text/javascript" src="scripts/jspdf.plugin.from_html.js"></script>
        <script type="text/javascript" src="scripts/FileSaver.js"></script>

        </head>
        -->
        <script src="scripts/jquery-1.10.2.js"></script>
        <script type="text/javascript" src="scripts/jspdf.js"></script>
        <script type="text/javascript" src="scripts/jspdf.plugin.standard_fonts_metrics.js"></script>
        <script type="text/javascript" src="scripts/jspdf.plugin.split_text_to_size.js"></script>
        <script type="text/javascript" src="scripts/jspdf.plugin.from_html.js"></script>
        <script type="text/javascript" src="scripts/FileSaver.js"></script>


        <span id="popupNotification"></span>

        <!--
        <div id="grid"></div>
        <div id="details"></div>
        <div id="testcase">
        <h1>
        <div id="Memorando"></div>
        </h1>
        </div>
        -->
        <style>
        #fieldlist li .k-widget:not(.k-tooltip),
        #fieldlist li .k-textbox {
        margin: 0 5px 5px 0;
        }
        </style>

        </div>
        </td>
        </tr>
        <tr>
        <td align="left" class="espacio1" valign="top" rowspan="1" colspan="1">
        <div align="left" id=""></div>
        </td>
        <td align="left" class="default" valign="top" rowspan="1" colspan="1">
        <div align="left" id=""></div>
        </td>
        <td align="left" class="default" colspan="2" valign="top" rowspan="1">
        <div align="left" id=""></div>
        </td>
        </tr>
        <tr>
        <td align="left" valign="top" rowspan="1" colspan="1">
        <div align="left" id=""></div>
        </td>
        <td align="left" valign="top" rowspan="1" colspan="1">
        <div align="left" id="">
        <div align="right" id=""></div>
        </div>
        </td>
        <td align="left" colspan="2" valign="top" rowspan="1">
        <div align="left" id="">

        <!--<head>

        <meta charset="utf-8">

        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.common.min.css">

        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.rtl.min.css">

        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.default.min.css">

        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.dataviz.min.css">

        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.dataviz.default.min.css">

        <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.2.624/styles/kendo.mobile.all.min.css">


        <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>

        <script src="http://cdn.kendostatic.com/2015.2.624/js/kendo.all.min.js"></script>


        <script type="text/javascript" src="scripts/jspdf.js"></script>

        <script type="text/javascript" src="scripts/jspdf.plugin.standard_fonts_metrics.js"></script>

        <script type="text/javascript" src="scripts/jspdf.plugin.split_text_to_size.js"></script>

        <script type="text/javascript" src="scripts/jspdf.plugin.from_html.js"></script>

        <script type="text/javascript" src="scripts/FileSaver.js"></script>


        </head>
        -->


        <!--
        <div id="grid"></div>

        <div id="details"></div>
        <div id="testcase">

        <h1>

        <div id="Memorando"></div>

        </h1>

        </div>

        -->

        <style>

        #fieldlist li .k-widget:not(.k-tooltip),

        #fieldlist li .k-textbox {

        margin: 0 5px 5px 0;

        }

        </style>

        </div>
        </td>
        </tr>
        <tr>
        <td align="left" class="espacio1" valign="top" rowspan="1" colspan="1">
        <div align="left" id=""></div>
        </td>
        <td align="left" class="default" valign="top" rowspan="1" colspan="1">
        <div align="left" id=""></div>
        </td>
        <td align="left" class="default" colspan="2" valign="top" rowspan="1">
        <div align="left" id=""></div>
        </td>
        </tr>
        <tr>
        <td align="left" class="default" valign="top" rowspan="1" colspan="1">
        <div align="left" id="">
        <br clear="all">
        </div>
        </td>
        <td align="left" class="default" valign="top" rowspan="1" colspan="1">
        <div align="left" id="">
        <div align="right" id="">
        <br clear="all">
        </div>
        </div>
        </td>
        <td align="left" class="default" colspan="2" valign="top" rowspan="1">
        <div align="left" id="">


        <style>

        #fieldlist li .k-widget:not(.k-tooltip),

        #fieldlist li .k-textbox {

        margin: 0 5px 5px 0;

        }

        </style>

        <br clear="all">
        </div>
        </td>
        </tr>
        <tr>
        <td align="left" class="default" valign="top" rowspan="1" colspan="1">
        <div align="left" id=""></div>
        </td>
        <td align="left" class="default" valign="top" rowspan="1" colspan="1">
        <div align="left" id=""></div>
        </td>
        <td align="left" class="default" colspan="2" valign="top" rowspan="1">
        <div align="left" id=""></div>
        </td>
        </tr>
        <tr>
        <td align="left" class="default" valign="top" rowspan="1" colspan="1">
        <div align="left" id=""></div>
        </td>
        <td align="left" class="default" valign="top" rowspan="1" colspan="1">
        <div align="left" id=""></div>
        </td>
        <td align="left" class="default" colspan="2" valign="top" rowspan="1">
        <div align="left" id="">


        <!--
        <script>

        $("#enviar").kendoButton();

        var button = $("#enviar").data("kendoButton");

        button.bind("click", function(e) {

        enviar();

        });

        </script>
        -->

        </div>
        </td>
        </tr>
        <tr>
        <td align="left" class="espacio1" valign="top" rowspan="1" colspan="1">
        <div align="left" id=""></div>
        </td>
        <td align="left" class="default" valign="top" rowspan="1" colspan="1">
        <div align="left" id=""></div>
        </td>
        <td align="left" class="default" colspan="2" valign="top" rowspan="1">
        <div align="left" id=""></div>
        </td>
        </tr>
        <tr>
        <td align="left" class="default" valign="top" rowspan="1" colspan="1">
        <div align="left" id=""></div>
        </td>
        <td align="left" class="default" valign="top" rowspan="1" colspan="1">
        <div align="left" id="">

        <!DOCTYPE html>
        <html>
        <!--
        <head>

        <script src="https://kendo.cdn.telerik.com/2015.2.902/js/jquery.min.js"></script>
        <script src="https://kendo.cdn.telerik.com/2015.2.902/js/kendo.all.min.js"></script>
        </head>
        -->
        <body>
        <div id="example">
        <span id="notification" style="display:none;"></span>

        <script id="emailTemplate" type="text/x-kendo-template">
        <div class="new-mail">
        <img src="images/loadingimage.gif" />
        <h3>#= title #</h3>
        <p>#= message #</p>
        </div>
        </script>

        <script id="successTemplate" type="text/x-kendo-template">
        <div class="upload-success" align="center">
        <img src="images/loading_2x.png" height="30" width="30" />
        <h3>#= message #</h3>
        </div>
        </script>
        <script id="errorTemplate" type="text/x-kendo-template">
        <div class="wrong-pass">
        <img src="images/error-icon.png" />
        <h3>#= title #</h3>
        <p>#= message #</p>
        </div>
        </script>
        <style>
        .demo-section p {
        margin: 3px 0 20px;
        line-height: 50px;
        }
        .demo-section .k-button {
        width: 250px;
        }
        .k-notification {
        border: 0;
        }
        /* Info template */
        .k-notification-info.k-group {
        background: rgba(0%,0%,0%,.7);
        color: #fff;
        }
        .new-mail {
        width: 300px;
        height: 100px;
        }
        .new-mail h3 {
        font-size: 1em;
        padding: 32px 10px 5px;
        }
        .new-mail img {
        float: left;
        margin: 30px 15px 30px 30px;
        }
        /* Error template */
        .k-notification-error.k-group {
        background: rgba(100%,0%,0%,.7);
        color: #ffffff;
        }
        .wrong-pass {
        width: 300px;
        height: 100px;
        }
        .wrong-pass h3 {
        font-size: 1em;
        padding: 32px 10px 5px;
        }
        .wrong-pass img {
        float: left;
        margin: 30px 15px 30px 30px;
        }
        /* Success template */
        .k-notification-upload-success.k-group {
        background: rgba(128,189,40,0.7);
        color: #fff;
        }
        .upload-success {
        width: 300px;
        top padding is 5px;
        bottom padding is 5px;
        line-height: 100px;
        resize: both;
        overflow: hidden;
        }
        .upload-success h3 {
        font-size: 1em;
        font-weight: normal;
        vertical-align: middle;
        text-align: justify;
        text-justify: inter-word;
        max-width:90%;
        line-height:100%;
        padding: 22px 10px;
        }
        .upload-success img {
        display: inline-block;
        vertical-align: middle;
        float: left;
        margin: 20px 15px 20px 20px;
        }

        </style>
        </div>
        </body>
        </html>

        </div>
        </td>
        <td align="left" class="default" valign="top" rowspan="1" colspan="1">
        <div align="left" id="">

        <div id="grid"></div>
        <div id="details"></div>
        <div id="testcase">
        <h1>
        <div id="Memorando"></div>
        </h1>
        </div>

        </div>
        </td>
        <td align="left" class="default" valign="top" rowspan="1" colspan="1">
        <div align="left" id=""></div>
        </td>
        </tr>
        </tbody>
        </table>
        <br clear="all">
        <table align="left" cellpadding="1" cellspacing="1" class="esconder" id="table2" width="100%">
        <colgroup span="1">
        <col width="100%" span="1">
        <col span="1">
        </colgroup>
        <tbody>
        <tr>
        <td align="left" class="ApSegDataVal" valign="top" rowspan="1" colspan="1">
        <div align="left" id="">
        <label class="ApSegDataslotLabel">usuario</label>
        <sfe:widget name="sbm.textfield" id="textField4"
                    args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'OpenEdge text field widget.', 'tabOrder':'0'}"/>

        </div>
        </td>
        <td align="left" class="ApSegDataVal" valign="top" rowspan="1" colspan="1">
        <div align="left" id="">
        <label class="ApSegDataslotLabel">ListaArchivos</label>
        <sfe:widget name="sbm.textarea" id="textArea1"
                    args="{'wrap':'Soft', 'rows':4, 'cols':20, 'visible':true, 'readonly':false, 'disabled':false, 'validationType':'none', 'validation':{ 'counterId':'textArea1_counter_span'}, 'toolTip':'OpenEdge textarea widget.', 'tabOrder':'0'}"/>

        <br clear="all">
        <label class="ApSegDataslotLabel">idreturn</label>
        <sfe:widget name="sbm.textfield" id="textField6"
                    args="{'type':'text', 'size':20, 'maxlength':50, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'integer', 'validation':{'minValue':'-2147483648', 'maxValue':'2147483647', 'isRequired':false, 'validateOn':['blur']}, 'type':'text', 'textfieldRequiredMsg':'Invalid Entry', 'toolTip':'OpenEdge text field widget.', 'tabOrder':'0'}"/>

        <br clear="all">
        <label class="ApSegDataslotLabel">estado</label>
        <sfe:widget name="sbm.textfield" id="textField7"
                    args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'OpenEdge text field widget.', 'tabOrder':'0'}"/>

        </div>
        </td>
        </tr>
        <tr>
        <td align="left" class="ApSegDataVal" valign="top" rowspan="1" colspan="1">
        <div align="left" id="">
        <br clear="all">
        <label class="ApSegDataslotLabel">nombrearchivo</label>
        <sfe:widget name="sbm.textfield" id="textField8"
                    args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'OpenEdge text field widget.', 'tabOrder':'0'}"/>

        </div>
        </td>
        <td align="left" class="ApSegDataVal" valign="top" rowspan="1" colspan="1">
        <div align="left" id="">
        <label class="ApSegDataslotLabel">ArchivoLC</label>
        <sfe:widget name="sbm.textarea" id="textArea2"
                    args="{'wrap':'Soft', 'rows':4, 'cols':20, 'visible':true, 'readonly':false, 'disabled':false, 'validationType':'none', 'validation':{ 'counterId':'textArea2_counter_span'}, 'toolTip':'OpenEdge textarea widget.', 'tabOrder':'0'}"/>

        </div>
        </td>
        </tr>
        <tr>
        <td align="left" class="ApSegDataVal" valign="top" rowspan="1" colspan="1">
        <div align="left" id="">
        <input class="ApScrnButton" name="SB_Name" id="button01" type="submit" tabindex="0" value="<bizsolo:getLabel
            name='Connection 7' type='LINK'/>" onMouseOut="this.className='ApScrnButton';"
        onMouseOver="this.className='ApScrnButtonHover';" onClick="clickedButton=this.name;this.onsubmit = new
        Function('return false');">

        <br clear="all">
        <br clear="all">
        <input class="ApScrnButton" name="SB_Name" id="button02" type="submit" tabindex="0" value="<bizsolo:getLabel
            name='Connection 8' type='LINK'/>" onMouseOut="this.className='ApScrnButton';"
        onMouseOver="this.className='ApScrnButtonHover';" onClick="clickedButton=this.name;this.onsubmit = new
        Function('return false');">

        <br clear="all">
        <br clear="all">
        <input class="ApScrnButton" name="SB_Name" id="button03" type="submit" tabindex="0" value="<bizsolo:getLabel
            name='Connection 11' type='LINK'/>" onMouseOut="this.className='ApScrnButton';"
        onMouseOver="this.className='ApScrnButtonHover';" onClick="clickedButton=this.name;this.onsubmit = new
        Function('return false');">

        <br clear="all">
        <input class="ApScrnButton" name="SB_Name" id="button04" type="submit" tabindex="0" value="<bizsolo:getLabel
            name='Connection 2' type='LINK'/>" onMouseOut="this.className='ApScrnButton';"
        onMouseOver="this.className='ApScrnButtonHover';" onClick="clickedButton=this.name;this.onsubmit = new
        Function('return false');">

        </div>
        </td>
        <td align="left" class="ApSegDataVal" valign="top" rowspan="1" colspan="1">
        <div align="left" id="">
        <label class="ApSegDataslotLabel">datos</label>
        <sfe:widget name="sbm.textarea" id="textArea3"
                    args="{'wrap':'Soft', 'rows':4, 'cols':20, 'visible':true, 'readonly':false, 'disabled':false, 'validationType':'none', 'validation':{ 'counterId':'textArea3_counter_span'}, 'toolTip':'OpenEdge textarea widget.', 'tabOrder':'0'}"/>

        <label class="ApSegDataslotLabel">returnId</label>
        <sfe:widget name="sbm.textfield" id="textField1"
                    args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'integer', 'validation':{'minValue':'-2147483648', 'maxValue':'2147483647', 'isRequired':false, 'validateOn':['blur']}, 'type':'text', 'textfieldRequiredMsg':'Invalid Entry', 'toolTip':'OpenEdge text field widget.', 'tabOrder':'0'}"/>

        <br clear="all">
        <label class="ApSegDataslotLabel">estado1</label>
        <sfe:widget name="sbm.textfield" id="textField3"
                    args="{'type':'text', 'size':20, 'maxlength':256, 'readonly':false, 'visible':true, 'disabled':false, 'validationType':'none', 'validation':{}, 'toolTip':'OpenEdge text field widget.', 'tabOrder':'0'}"/>

        <br clear="all">
        </div>
        </td>
        </tr>
        </tbody>
        </table>
        <div align="center" id=""></div>


        <div id="resizablepanel" style="display:none">
        <div class="hd">Alert Dialog</div>
        <div class="bd"></div>
        <div class="ft"></div>
        </div>
        <div id="southDiv"></div></form>
        </body>

        <script language="JavaScript">
        <!--
        function beforeInitControls() {
        }
        -->
        </script>
        <script language="JavaScript">
        <!--
        function userValidationJavascript() {
        return true;
        }
        -->
        </script>
        <sbm:dataSources appName="Documentos" appType="bizsolo">
        </sbm:dataSources>
        <script language="JavaScript">
        <!--
        sessionStorage.getItem("datEmpr");
        sessionStorage.setItem("datEmpr", "prueba");
        var usuario = sessionStorage.getItem("usuario");
        var nombrearchivo;
        function onShow(e) {
        if (!$("." + e.sender._guid)[1]) {
        var element = e.element.parent(), eWidth = element.width(), eHeight = element
        .height(), wWidth = $(window).width(), wHeight = $(window)
        .height(), newTop, newLeft;
        newLeft = Math.floor(wWidth / 2 - eWidth / 2);
        newTop = Math.floor(wHeight / 2 - eHeight / 2);
        e.element.parent().css({
        top : newTop,
        left : newLeft
        });
        }
        }
        function alcargar() {
        try {
        if (!usuario) {
        usuario = "aduarte";
        }
        if (!sbm.util.getValue(textField7)) {
        sbm.util.setValue("textField4", usuario);
        // sbm.util.setValue("textField4","aduarte");
        sessionStorage.setItem("consumoServ", "1");
        document.getElementById("button02").click();
        }

        sbm.util.setValue("textField4", usuario);
        if ((sbm.util.getValue("textArea1")) != "") {
        var docs1 = sbm.util.getValue("textArea1");
        var docs2 = JSON.parse(docs1);
        var docs = [];

        for (var x = 0; x < docs2.ttfiles.length; x++) {
        docs.push({
        nomfile : docs2.ttfiles[x].nomfile,
        tamfile : docs2.ttfiles[x].tamfile,
        fecfile : docs2.ttfiles[x].fecfile
        });
        }
        $(document).ready(function() {
        var grid = $("#grid").kendoGrid({
        dataSource : {
        data : docs,
        },
        selectable : true,
        sortable:true,
        columns : [ {
        field : "nomfile",
        title : "Documento"
        },
        {
        field : "fecfile",
        title : "Fecha de Creaci&oacute;n"
        },{
        field : "tamfile",
        title : "Tama&ntilde;o de Archivo"
        }, {
        command : {
        name : "descargar",
        className : "botonDescargar",
        text : "",
        click : showDetails
        },
        title : " "
        }, {
        command : {
        name : "ver",
        className : "botonVer",
        text : "",
        click : htmldoc
        },
        title : " "
        }, {
        command : {
        name : "descargapdf",
        className : "botonPdf",
        text : "",
        click : pdf
        },
        title : " "
        } ],
        }).data("kendoGrid");
        });
        }
        if ($("#grid").data("kendoGrid")) {
        var grid = $("#grid").data("kendoGrid");
        for (var i = 1; i < grid.columns.length; i++) {
        grid.autoFitColumn(i);
        }

        var gridData = grid.dataSource.view();
        for (var i = 0; i < gridData.length; i++) {
        var filename=gridData[i].nomfile;
        var res = filename.split(".");
        filename = res[0];
        extension = res[1];

        var currentUid = gridData[i].uid;
        var currentRow = grid.table.find("tr[data-uid='" + currentUid + "']");
        var ver = $(currentRow).find(".botonVer");
        var expdf= $(currentRow).find(".botonPdf");

        if(extension=="pdf"){
        expdf.prop('disabled', true);
        expdf.attr("class", "k-button k-button-icontext botonNoPdf k-grid-ver");
        ver.prop('disabled', true);
        ver.attr("class", "k-button k-button-icontext botonNoVer k-grid-ver");
        }
        }

        }
        if ((sbm.util.getValue("textField7"))
        .indexOf("No hay Documentos creados en esa fecha") != -1) {
        var notificacionError = $("#notification").kendoNotification({
        position : {
        pinned : true,
        top : 30,
        right : 30
        },
        autoHideAfter : 0,
        stacking : "down",
        show : onShow,
        templates : [ {
        type : "error",
        template : $("#errorTemplate").html()
        } ]
        }).data("kendoNotification");
        notificacionError.show({
        title : "Ocurrio un Error",
        message : sbm.util.getValue("textField7")
        }, "error");
        }
        if (sbm.util.getValue("textArea2") != "") {
        demoFromHTML();
        }
        if (sbm.util.getValue("textField1") != "0"
        && sbm.util.getValue("textArea3") == "") {
        if (sbm.util.getValue("textField1").indexOf(
        "No se existe informacion para el usuario") !== "-1") {
        mensajeAlerta("No se existe informacion para el usuario "
        + usuario);
        } else {
        mensajeAlerta(sbm.util.getValue("textField3"));
        }
        }
        } catch (e) {
        alert(e);
        }
        }

        function showDetails(e) {
        try {
        sessionStorage.setItem("tipo", "archivo");
        e.preventDefault();
        var row = $(e.target).closest("tr");
        var item = $("#grid").data("kendoGrid").dataItem(row);
        item = item.nomfile;
        item = item.toString();
        sbm.util.setValue("textField9", item);
        sbm.util.setValue("textField8", item);
        formWidgetHandler.saveDataSlots();
        document.getElementById("button03").click();
        } catch (e) {
        alert(e);
        }
        }

        function htmldoc(e) {
        try {
        sessionStorage.setItem("tipo", "html");
        e.preventDefault();
        var row = $(e.target).closest("tr");
        var item = $("#grid").data("kendoGrid").dataItem(row);
        item = item.nomfile;
        item = item.toString();
        sbm.util.setValue("textField9", item);
        sbm.util.setValue("textField8", item);
        formWidgetHandler.saveDataSlots();
        document.getElementById("button03").click();
        } catch (e) {
        alert(e);
        }
        }
        function pdf(e) {
        try {
        sessionStorage.setItem("tipo", "pdf");
        e.preventDefault();
        var row = $(e.target).closest("tr");
        var item = $("#grid").data("kendoGrid").dataItem(row);
        item = item.nomfile;
        item = item.toString();
        sbm.util.setValue("textField9", item);
        sbm.util.setValue("textField8", item);
        formWidgetHandler.saveDataSlots();
        document.getElementById("button04").click();
        } catch (e) {
        alert(e);
        }
        }

        function demoFromHTML() {
        try {
        var archivo = sbm.util.getValue("textArea2");
        var nombrearchivo = sbm.util.getValue("textField8");
        if (sessionStorage.getItem("tipo") == "archivo") {
        download(nombrearchivo, archivo, "archivo");
        } else if (sessionStorage.getItem("tipo") == "pdf") {
        download(nombrearchivo, archivo, "pdf");
        } else if (sessionStorage.getItem("tipo") == "html") {
        download(nombrearchivo, archivo, "html");
        }
        } catch (e) {
        alert(e);
        }
        }
        function download(filename, text, tipo) {
        var res = filename.split(".");
        filename = res[0];
        extension = res[1];
        try {
        if (tipo == "archivo") {
        filename = filename + "." + extension;
        if (extension == "pdf") {
        var byteCharacters = atob(text);
        var byteNumbers = new Array(byteCharacters.length);
        for (var i = 0; i < byteCharacters.length; i++) {
        byteNumbers[i] = byteCharacters.charCodeAt(i);
        }
        var byteArray = new Uint8Array(byteNumbers);
        var blob = new Blob([ byteArray ], {
        type : "application/pdf"
        });
        saveAs(blob, filename);
        } else {
        var blob = new Blob([ text ]);
        saveAs(blob, filename);
        }
        } else if (tipo == "html") {
        filename = filename + ".pdf";
        if (extension == "pdf") {

        var byteCharacters = atob(text);
        var byteNumbers = new Array(byteCharacters.length);
        for (var i = 0; i < byteCharacters.length; i++) {
        byteNumbers[i] = byteCharacters.charCodeAt(i);
        }
        var byteArray = new Uint8Array(byteNumbers);
        var blob = new Blob([ byteArray ], {
        type : "application/pdf"
        });
        saveAs(blob, filename);
        } else {
        var blob = new Blob([ text ]);
        var fileURL = URL.createObjectURL(blob);
        window.open(fileURL);
        }
        } else if (tipo == "pdf") {
        filename = filename + ".pdf";
        if (extension == "pdf") {
        var byteCharacters = atob(text);
        var byteNumbers = new Array(byteCharacters.length);
        for (var i = 0; i < byteCharacters.length; i++) {
        byteNumbers[i] = byteCharacters.charCodeAt(i);
        }
        var byteArray = new Uint8Array(byteNumbers);
        var blob = new Blob([ byteArray ], {
        type : "application/pdf"
        });
        saveAs(blob, filename);
        return;
        } else {
        var blob = new Blob([ text ]);
        saveAs(blob, filename);
        return;
        }
        }
        } catch (e) {
        alert(e);
        }
        }

        function mensajeAlerta(msj) {
        var notificacionError = $("#notification").kendoNotification({
        position : {
        pinned : true,
        top : 30,
        right : 30
        },
        autoHideAfter : 0,
        stacking : "down",
        show : onShow,
        templates : [ {
        type : "error",
        template : $("#errorTemplate").html()
        } ]
        }).data("kendoNotification");
        notificacionError.show({
        title : "Ocurrio un Error",
        message : msj
        }, "error");
        }

        function form_onLoad(eventContext){
        alcargar();}

        -->
        </script>
        <script language="JavaScript" src="scripts/jquery.min.js"></script>
        <script language="JavaScript" src="scripts/kendo.all.min.js"></script>
        <!--Initialize extensible widgets.-->
        <script language="JavaScript">
        <!--
        var _dateFormats = {date:'<%=bean.getPropString(PublicResources.JS_CALENDAR_DATE_FORMAT)%>',
        dateOnly:'<%=bean.getPropString(PublicResources.JS_CALENDAR_DATE_ONLY_FORMAT)%>'};

        var allWidgets = [{widget:'textField4', bound:'true', editable:'true', type:'sbm.textfield', source:
        {type:'DATASLOT', dataSlotName:'usuario', dataSlotType:'ABL_CHARACTER'}, target:{type:'DATASLOT',
        dataSlotName:'usuario', dataSlotType:'ABL_CHARACTER'}, dsType:'ABL_CHARACTER', service:'false'},
        {widget:'textArea1', bound:'true', editable:'true', type:'sbm.textarea', source: {type:'DATASLOT',
        dataSlotName:'ListaArchivos', dataSlotType:'ABL_LONGCHAR'}, target:{type:'DATASLOT',
        dataSlotName:'ListaArchivos', dataSlotType:'ABL_LONGCHAR'}, dsType:'ABL_LONGCHAR', service:'false'},
        {widget:'textField6', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT',
        dataSlotName:'idreturn', dataSlotType:'ABL_INTEGER'}, target:{type:'DATASLOT', dataSlotName:'idreturn',
        dataSlotType:'ABL_INTEGER'}, dsType:'ABL_INTEGER', service:'false'},
        {widget:'textField7', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT',
        dataSlotName:'estado', dataSlotType:'ABL_CHARACTER'}, target:{type:'DATASLOT', dataSlotName:'estado',
        dataSlotType:'ABL_CHARACTER'}, dsType:'ABL_CHARACTER', service:'false'},
        {widget:'textField8', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT',
        dataSlotName:'nombrearchivo', dataSlotType:'ABL_CHARACTER'}, target:{type:'DATASLOT',
        dataSlotName:'nombrearchivo', dataSlotType:'ABL_CHARACTER'}, dsType:'ABL_CHARACTER', service:'false'},
        {widget:'textArea2', bound:'true', editable:'true', type:'sbm.textarea', source: {type:'DATASLOT',
        dataSlotName:'ArchivoLC', dataSlotType:'ABL_LONGCHAR'}, target:{type:'DATASLOT', dataSlotName:'ArchivoLC',
        dataSlotType:'ABL_LONGCHAR'}, dsType:'ABL_LONGCHAR', service:'false'},
        {widget:'textArea3', bound:'true', editable:'true', type:'sbm.textarea', source: {type:'DATASLOT',
        dataSlotName:'datos', dataSlotType:'ABL_LONGCHAR'}, target:{type:'DATASLOT', dataSlotName:'datos',
        dataSlotType:'ABL_LONGCHAR'}, dsType:'ABL_LONGCHAR', service:'false'},
        {widget:'textField1', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT',
        dataSlotName:'returnId', dataSlotType:'ABL_INTEGER'}, target:{type:'DATASLOT', dataSlotName:'returnId',
        dataSlotType:'ABL_INTEGER'}, dsType:'ABL_INTEGER', service:'false'},
        {widget:'textField3', bound:'true', editable:'true', type:'sbm.textfield', source: {type:'DATASLOT',
        dataSlotName:'estado1', dataSlotType:'ABL_CHARACTER'}, target:{type:'DATASLOT', dataSlotName:'estado1',
        dataSlotType:'ABL_CHARACTER'}, dsType:'ABL_CHARACTER', service:'false'}
        ];
        var businessObjects = [];
        var formWidgetHandler;

        sbm.utils.onDOMReady = function() {
        YAHOO.util.Event.onDOMReady(function(){
        formWidgetHandler = new
        FormWidgetHandler(allWidgets,form_onLoad,{processName:'Documentos',adapletCache:{'user':''}},'<%=request.getParameter(BizSoloRequest.BSS_FIID)%>
        ');
        });
        }
        Ext.onReady(function(){
        var viewport = new Bm.util.BmViewport('',{resultComponentXtype:'container'});

        });
        sbm.utils.onFormSubmit = function() {
        if(!formWidgetHandler.validateWidgets()) return false;
        try{
        if(!userValidationJavascript()) return false;
        sbm.utils.handleFormSubmit();
        }catch(e){return false;}
        document.form.action='<%=response.encodeURL("Start.jsp")%>';
        if(allWidgets.length > 0)formWidgetHandler.saveDataSlots();
        return true;
        }
        -->
        </script>

        </html>